language: node_js
node_js:
- '0.11'
- '0.10'
sudo: false
cache:
  directories:
    - node_modules
install: npm install
env:
  global:
  - secure: Bx3GZSFR2kBrgW72O1jbnKIgtaj5ItotigKYATBOAd8NhmXGETbI4t7kLbBcB/oQXpa4i00EPG62sUA7iiJJpXb0gPBU0/1FDij4uYvUTg5cD7Q8iMJ6auDq1VN906zbr+GgbHw6kgvNcAOozkMO3TAioMr4xLNLBmjD9E+APOWAcqiDyfqTXDTP6E//dmmCJ6sjX7qPEhkyhjO9c4Fa6vtsL9pJi+6Slo/CofOl6Bjnb9OZmXevdwQMjen5WIbIGo1TK5EnryKtPaxDxf2Uh41kaSkJQNPh9dYARndmqOK0Z+afDFb9YVirw+d9slBG5rNeMoXHyZshi9Y1rG9V+Yqz4rKWEKJAz5pil8BtO8V+WgzbmiY0KK4TKe+qmdy73yGRc659stwRiskI2zZ384WoJPWCFv0Om0uy9fZVZc0UPHL6RZREPfJ/fztqF2A4aV1yXenbGL4PH2ApikLPLAnUd+u5++J+ZgHokgSeXs1P3PFW4yhYRKs6AdLAwYMC1lEhSUBYHJJowUa+p66yvXE056CgsULRQpL1LYcUkKMblYeejQFycMWg580YLKYENeei1vHdXyidQ4oFe6xLKi3qYEzicJeyy8ENdii7rlbOJPpx5UHQuYME8a3YUUOhxDAWzHdQPFgQkues7cjyuMCnW7aro3TDkfGqB+sVTEs=
  - secure: g4VQq7qurIfCENrJUjNzQzgix9/7gffPMkY2PMpEAP4UOxm51dE+9tEhSD0Nf7BJmdrsLm2tiL2QiOXNB2vkIXbULIX3saa0SogLvKOF9o9vEp6shBxtlY4kViTEL892D+GyQgRCwAvBqPdb79ASkNLdRCB/x7vFq60w0Ic29sYQkSk6OyCJluHgZ/+LXkf1HGn60UC46+kSukTP4ZptK97CbvHkotnwGVe2iJ20ByGgivzzLNkyOsr4PzQq4EdS50fQ2sAePMdKBhMs1wxWNYb+eoLWs8h6UprkIiEHTGLYNvpLqXN1gp1Rj8Btf39ybrKRmPX4FNwsNI+MTkZCHtnRzEZFfD7RjSNZUnjqy72r7YZRabqhI4P/vYGZ7GCnqDUfl2Q0lhnt8dw7LIQ0+sB2jGn/JrXuNyjRlh5n1ZTvUzfcgmy+x1LzZxpLXUdb3mlQsj22MV5jPGeKOeaU3MeELAMG/iZEV293VhKqBrCICV1hPNJgT2oBAYbAfnDo8R5DED/CPdfSUeH8wWckcTiWY7971G7CYW/z98IThXKQ/oL0W488oEge8ji6psSKFDtuP95RMP/IP/aMIfvmYRuN3bxTxt8hmVNwBQ5ou2zXFLgQ4/FNaVug8yPyQxfM9dAyhUhEsL665p/X932cgUouNuKYu205P/ZMMt0Th8w=
